// gui_ids.h

#ifndef GUI_IDS_H
#define GUI_IDS_H

enum
{
    WINDOW_ESCAPE_LIST_BOX, //Escape Liste déroulée "Menu"
    UNDERSTOOD_BUTTON, //Allow also to close an information window

    WINDOW_VALUE,
    WINDOW_BUTTON,
    WINDOW_CHECK_BOX,
    WINDOW_COMBO_BOX,
    WINDOW_COMBO_CHOICE_1,
    WINDOW_COMBO_CHOICE_2,
    WINDOW_COMBO_CHOICE_3,
    WINDOW_LIST_BOX,
    WINDOW_SCROLLBAR,
    WINDOW_SPIN_BOX,

    MENU_NEW_GAME,
    MENU_QUIT,
    MENU_BOUNDING_BOX,
    MENU_NORMALS,
    MENU_TRIANGLES,
    MENU_TRANSPARENCY,
    MENU_ABOUT,

    WINDOW_BEGIN,
    WINDOW_ESCAPE,
    WINDOW_ROOM_1,
};

#endif
