// gui_ids.h

#ifndef GUI_IDS_H
#define GUI_IDS_H

enum
{
    WINDOW_ESCAPE_LIST_BOX, //Escape Liste déroulée "Menu"
    UNDERSTOOD_BUTTON, //Allow also to close an information window
    ClOSE_BUTTON_ENIGM_1,
    ClOSE_BUTTON_ENIGM_2,

    WINDOW_SPIN_BOX,


    WINDOW_BEGIN,
    WINDOW_ESCAPE,
    WINDOW_ROOM_1,
    WINDOW_ROOM_2,
    WINDOW_ENIGM_1,
    WINDOW_ANSWER_ENIGM_1,
    WINDOW_ENIGM_2,
    WINDOW_ANSWER_ENIGM_2,

    //ENIGM 1 : BIRTH DATE
    TRY_BUTTON_1,
    DAY_SPIN,
    MONTH_SPIN,
    YEAR_SPIN,

    //ENIGM FINAL
    TRY_BUTTON_FINAL,
    CLOSE_BUTTON_ENIGM_FINAL,
    WINDOW_ENIGM_FINAL,
    FINAL_SPIN,

    WINDOW_BACK_ROOM_0,

    CLOSE_GAME,
    END_GAME


};

#endif
